{
 "title": "Edge server dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(flask_http_request_total{service=~\".*app.*\"} [10s]))",
     "legendFormat": "Average"
    },
    {
     "expr": "sum by (pod) (\n  sum by (pod, status) (\n    rate(flask_http_request_total{service=~\".*app.*\"} [10s])\n  )\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=~\"app.*\"} [30s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=~\"app.*\"} [30s])\n    )\n)",
     "legendFormat": "Average"
    },
    {
     "expr": "avg by (pod) (\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=~\"app.*\"} [30s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=~\"app.*\"} [30s])\n    )\n)",
     "legendFormat": "{{pod}} average"
    }
   ]
  },
  {
   "title": "CPU Utilization % ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"app.*\"}[1m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{container=~\"app.*\"}/container_spec_cpu_period{container=~\"app.*\"}) by (pod_name, container_name)*100",
     "legendFormat": "{{pod}} Total"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"app.*\"}[1m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{container=~\"app.*\"}/container_spec_cpu_period{container=~\"app.*\"}) by (pod_name, container_name)*100",
     "legendFormat": "{{pod}} cpu"
    }
   ]
  },
  {
   "title": "CPU cores ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  rate(container_cpu_usage_seconds_total{ container=~\"app.*\"} [1m])"
    },
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"app.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum  by (pod) (container_memory_working_set_bytes{pod=~\"app.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Number of Requests per Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(flask_http_request_total{service=~\"app.*\"} [30s])))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of edge-server-cv pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(count by (pod) (container_memory_usage_bytes{container=~\"app.*\"}))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}