{
 "title": "Druidnet dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "γ parameter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "2*sum(req_rate_app1) + sqrt(sum(flower_events_total{type=\"task-received\",worker=\"celery@green_worker\"})-sum(flower_events_total{type=\"task-succeeded\",worker=\"celery@green_worker\"})) ",
     "legendFormat": "γ for app1"
    },
    {
     "expr": "3*sum(req_rate_app2) + sqrt(sum(flower_events_total{type=\"task-received\",worker=\"celery@red_worker\"})-sum(flower_events_total{type=\"task-succeeded\",worker=\"celery@red_worker\"}))",
     "legendFormat": "γ for app2"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=~\"app.*\"} [30s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=~\"app.*\"} [30s])\n    )\n)",
     "legendFormat": "Average"
    },
    {
     "expr": "avg by (pod) (\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=~\"app1\"} [30s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=~\"app1\"} [30s])\n    )\n)",
     "legendFormat": "{{pod}} average"
    },
    {
     "expr": "avg by (pod) (\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=~\"app2\"} [30s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=~\"app2\"} [30s])\n    )\n)",
     "legendFormat": "{{pod}} average"
    }
   ]
  },
  {
   "title": "Tasks Not Finished",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum((flower_events_total{type=\"task-received\",worker=\"celery@green_worker\"}-flower_events_total{type=\"task-received\",worker=\"celery@green_worker\"} offset 30m)) - sum((flower_events_total{type=\"task-succeeded\",worker=\"celery@green_worker\"}-flower_events_total{type=\"task-succeeded\",worker=\"celery@green_worker\"} offset 30m))",
     "legendFormat": "not finished app2"
    },
    {
     "expr": "sum((flower_events_total{type=\"task-received\",worker=\"celery@red_worker\"}-flower_events_total{type=\"task-received\",worker=\"celery@red_worker\"} offset 30m)) - sum(flower_events_total{type=\"task-succeeded\",worker=\"celery@red_worker\"}-flower_events_total{type=\"task-succeeded\",worker=\"celery@red_worker\"} offset 30m)\n",
     "legendFormat": "not finished app1"
    }
   ]
  },
  {
   "title": "CPU cores ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  rate(container_cpu_usage_seconds_total{ container=~\"app.*\"} [1m])",
     "legendFormat": "{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "queue_size", "legendFormat": "Queue_current_size max" },
    { "expr": "req_rate_app1", "legendFormat": "Request_Rate_App1" },
    { "expr": "req_rate_app2", "legendFormat": "Request_Rate_App2" }
   ]
  },
  {
   "title": "CPU Utilization % ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"app.*\"}[1m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{container=~\"app.*\"}/container_spec_cpu_period{container=~\"app.*\"}) by (pod_name, container_name)*100",
     "legendFormat": "{{pod}} Total CPU % of limit"
    },
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container=~\"app.*\"}[1m])",
     "legendFormat": "{{pod}} cpu throttling"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"app1.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}} cpu % "
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"app2.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}} cpu %"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"app.*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (pod)(container_memory_working_set_bytes{pod=~\"app.*\"})",
     "legendFormat": "{{pod}} Pod"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(flask_http_request_total{service=~\".*app.*\"} [10s]))",
     "legendFormat": "Average Rate per 10s"
    },
    {
     "expr": "sum by (pod) (\n  sum by (pod, status) (\n    rate(flask_http_request_total{service=~\".*app.*\"} [10s])\n  )\n)",
     "legendFormat": "{{pod}} Rate per 10s"
    },
    {
     "expr": "sum (rate(flask_http_request_total{service=~\".*web.*\"} [10s]))",
     "legendFormat": "Controller Rate per 10s"
    }
   ]
  },
  {
   "title": "Total Number of Requests per Interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(flask_http_request_total{service=~\"app.*\"} [30s])))",
     "legendFormat": "Total on apps"
    },
    {
     "expr": "round(sum(increase(flask_http_request_total{service=~\"web.*\",status=\"202\"} [30s])))",
     "legendFormat": "Total on controller"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(count by (pod) (container_memory_usage_bytes{container=~\"app.*\"}))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}