apiVersion: apps/v1 
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: dspatharakis/controller_druidnet:edge-server
        name: app1 #edge-server-cv
        resources:
          limits:
            cpu: "1000m"
            memory: "6Gi"
          requests:
            cpu: "1000m"
            memory: "6Gi"
        env:
        - name: EDGE_SERVER_PORT
          value: '8000'
        - name: CPU_LIMIT
          value: '4'
        - name: PROMETHEUS_MULTIPROC_DIR
          value: '/tmp'
        ports:
        - name: es-port
          containerPort: 8000
#     spec:
#       containers:
#         - args:
#             - python
#             - manage_object.py
#             - run
#             - -h
#             - 0.0.0.0
#             - --no-debugger
#           env:
#             - name: FLASK_APP
#               value: object_repo/__init__.py
#           image: dspatharakis/controller_druidnet:app1
#           name: app1
#           ports:
#             - containerPort: 5000
#           resources: {}
#       restartPolicy: Always
# status: {}
