apiVersion: v1
kind: Service
metadata:
  name: app2
  labels:
    app: app2
spec:
  ports:
  - name: app2-port
    port: 6005
    nodePort: 30802
    targetPort: 5000
  selector:
    app: app2
  type: NodePort
---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: app2
  labels:
    app: app2
spec:
  selector:
    matchLabels:
      app: app2
  endpoints:
  - port: app2-port
    interval: 1s