apiVersion: v1
kind: Service
metadata:
  name: beat-worker
  labels:
    app: beat-worker
spec:
  ports:
  - name: beat-worker-port
    port: 6004
    nodePort: 30805
    targetPort: 8000
  selector:
    app: beat-worker
  type: NodePort
---
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: beat-worker
  labels:
    app: beat-worker
spec:
  selector:
    matchLabels:
      app: beat-worker
  endpoints:
  - port: beat-worker-port
    interval: 1s


