version: '3.8'

services:
  app1:
    build: .
    image: dspatharakis/controller_druidnet:app1
    container_name: app1
    ports:
      - 6004:5000
    command: python manage_object.py run -h 0.0.0.0
    environment:
      - FLASK_APP=object_repo/__init__.py
    depends_on:
      - web
  app2:
    build: .
    image: dspatharakis/controller_druidnet:app2
    container_name: app2
    ports:
      - 6005:5000
    command: python manage_object.py run -h 0.0.0.0

    environment:
      - FLASK_APP=object_repo/__init__.py
    depends_on:
      - web
  web:
    build: .
    image: dspatharakis/controller_druidnet:web
    container_name: web
    ports:
      - 5004:5000
    command: ./run_server.sh
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
  db:
    image: dspatharakis/controller_druidnet:db
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env.dev
  red_worker:
    build: .
    image: dspatharakis/controller_druidnet:red_worker
    command: celery worker -Q red --app=project.tasks.celery -c=1 --loglevel=info --logfile=project/logs/celery.log -n red_worker
    env_file:
      - .env.dev
    depends_on:
      - web
      - app1
      - db
      - redis 

  green_worker:
    build: .
    image: dspatharakis/controller_druidnet:green_worker
    command: celery worker -Q green --app=project.tasks.celery -c=1 --loglevel=info --logfile=project/logs/celery.log -n green_worker
    env_file:
      - .env.dev
    depends_on:
      - web
      - app2
      - db
      - redis
  
  beat_worker:
    build: .
    image: dspatharakis/controller_druidnet:beat_worker
    command: celery worker -Q celery_periodic --app=project.tasks.celery --loglevel=info --logfile=project/logs/celery.log  
    env_file:
      - .env.dev
    depends_on:
      - web
      - db
      - redis

  celery_beat:
    build: .
    image: dspatharakis/controller_druidnet:celery_beat
    command: celery -A project.celery beat -l info
    env_file:
      - .env.dev
    depends_on:
      - web
      - redis
      - db

  dashboard:
    build: .
    image: dspatharakis/controller_druidnet:dashboard
    command:  flower --app=project.tasks.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    env_file:
      - .env.dev
    depends_on:
      - web
      - redis
      - beat_worker
      - green_worker
      - red_worker

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

