apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
        - args:
            - mongod
          env:
            - name: MONDODB_LOG_DIR
              value: /dev/null
            - name: MONGODB_DATA_DIR
              value: /data/db
            - name: MONGO_INITDB_DATABASE
              value: flaskdb
          image: mongo:4.0.8
          name: mongodb
          resources: {}
      restartPolicy: Always
status: {}
